{
 "title": "Conditions",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  location AS metric,\n  temperature\nFROM conditions\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  location AS metric,\n  humidity\nFROM conditions\nWHERE\n  $__timeFilter(time)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Last Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  location,\n  LOCF(last(temperature,\"time\")) AS \"temperature\"\nFROM conditions\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  location,\n  LOCF(last(humidity,\"time\")) AS \"last_humidity\"\nFROM conditions\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY location"
    }
   ]
  },
  {
   "title": "1min temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n time_bucket_gapfill('1 minutes', time) AS \"time\",\r\n location,\r\n LOCF(avg(temperature)) as temperature\r\nFROM conditions\r\nWHERE\r\n  $__timeFilter(\"time\")\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "1min humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n time_bucket_gapfill('1 minutes', time) AS \"time\",\r\n location,\r\n LOCF(avg(humidity)) as humidity\r\nFROM conditions\r\nWHERE\r\n  $__timeFilter(\"time\")\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "5min temprature/humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n time_bucket_gapfill('5 minutes', time) AS \"time\",\r\n location,\r\n LOCF(avg(temperature)) as temperature,\r\n LOCF(avg(humidity)) as humidity\r\nFROM conditions\r\nWHERE\r\n  $__timeFilter(\"time\")\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "オフィス 直近5min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n time_bucket_gapfill('5 minutes', time) AS \"time\",\r\n location,\r\n LOCF(avg(temperature)) as temperature,\r\n LOCF(avg(humidity)) as humidity\r\nFROM conditions\r\nWHERE\r\n  $__timeFilter(\"time\")\r\n  AND location = 'オフィス'\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "家 直近5min",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n time_bucket_gapfill('5 minutes', time) AS \"time\",\r\n location,\r\n LOCF(avg(temperature)) as temperature,\r\n LOCF(avg(humidity)) as humidity\r\nFROM conditions\r\nWHERE\r\n  $__timeFilter(\"time\")\r\n  AND location = '家'\r\nGROUP BY 1,2\r\nORDER BY 1,2"
    }
   ]
  }
 ]
}