version: "3"

volumes:
  postgresql: {}
  pgadmin: {}
  grafana: {}

services:
  timescaledb:
    image: timescale/timescaledb:2.2.1-pg13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timeseries
      - TS_TUNE_MAX_CONNS=1000
    volumes:
      - postgresql:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - timescaledb
    image: dpage/pgadmin4:5.2
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin

  grafana:
    depends_on:
      - timescaledb
    image: grafana/grafana:7.5.2-ubuntu
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
      - grafana:/var/lib/grafana
