version: "3"

volumes:
  postgresql: {}
  pgadmin: {}
  grafana: {}

services:
  timescaledb:
    image: timescale/timescaledb:2.1.1-pg13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=timeseriese
    volumes:
      - postgresql:/var/lib/postgresql/data
      # when you want run sql / bash on provisioning
      #- ./postgresq/ldocker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:5.1
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - timescaledb

  grafana:
    image: grafana/grafana:7.5.2-ubuntu
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
      - grafana:/var/lib/grafana
    depends_on:
      - timescaledb
